import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "3fc4eb83974eb64ecb298856b0db70cc3055af57"
    public static let mdkTag = "marmotkit-v0.9.12"
    public static let builtAt = "2026-08-13T12:40:00Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export"
}
