import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "4e056e708afeb86fb4e62049b73c8ad4155ddf1a"
    public static let mdkTag = "marmotkit-snapshot-4e056e708afeb86fb4e62049b73c8ad4155ddf1a"
    public static let builtAt = "2026-08-11T13:57:47Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export"
}
