import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "f734b31176ad628d5e5dfcb047f80e4ec7bb826c"
    public static let mdkTag = "marmotkit-v0.9.18"
    public static let builtAt = "2026-09-05T09:01:34Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export"
}
