#!/usr/bin/env bash
# Rebuild the MarmotKit bindings from the MDK Rust workspace and
# re-vendor them into this iOS app. Run this whenever the Rust side
# (crates/marmot-uniffi or any crate it depends on) changes.
#
# You do NOT need to run this for Swift-only changes — just build & run the
# app in Xcode (Cmd+R). The xcframework is a prebuilt binary; Xcode links
# it but never recompiles the Rust.
#
# Usage:
#   ./scripts/sync-bindings.sh
#   MDK_DIR=/path/to/mdk ./scripts/sync-bindings.sh
#
# Override MDK_DIR if the MDK repo isn't the sibling default.

set -euo pipefail

IOS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
if [[ -z "${MDK_DIR:-}" ]]; then
    if [[ -n "${DARKMATTER_DIR:-}" ]]; then
        echo "warning: DARKMATTER_DIR is deprecated; use MDK_DIR instead." >&2
        MDK_DIR="$DARKMATTER_DIR"
    else
        MDK_DIR="$IOS_DIR/../mdk"
    fi
fi

if [[ ! -d "$MDK_DIR" ]]; then
    echo "error: can't find MDK repo at $MDK_DIR" >&2
    echo "       set MDK_DIR to point at the marmot-protocol/mdk repo." >&2
    exit 1
fi

MDK_DIR="$(cd "$MDK_DIR" && pwd)"

VENDOR_DIR="$IOS_DIR/Vendored/MarmotKit"
OUTPUT_DIR="$MDK_DIR/crates/marmot-uniffi/output"

if [[ ! -d "$MDK_DIR/crates/marmot-uniffi" ]]; then
    echo "error: can't find marmot-uniffi crate at $MDK_DIR/crates/marmot-uniffi" >&2
    echo "       set MDK_DIR to point at the marmot-protocol/mdk repo." >&2
    exit 1
fi

export OTLP_EXPORT="${OTLP_EXPORT:-1}"
echo "==> Building MarmotKit.xcframework from $MDK_DIR"
"$MDK_DIR/crates/marmot-uniffi/xcframework.sh"

echo "==> Re-vendoring into $VENDOR_DIR"
rsync -a --delete \
    "$OUTPUT_DIR/MarmotKit.xcframework/" \
    "$VENDOR_DIR/MarmotKit.xcframework/"
cp "$OUTPUT_DIR/MarmotKit.swift" "$VENDOR_DIR/Sources/MarmotKit/MarmotKit.swift"

echo "==> Stripping debug symbols from vendored static libraries"
while IFS= read -r -d '' library; do
    xcrun strip -S -x "$library"
done < <(find "$VENDOR_DIR/MarmotKit.xcframework" -name 'libmarmot_uniffi.a' -print0)

echo "==> Tidying generated text artifacts"
find "$VENDOR_DIR" \( -name '*.swift' -o -name '*.h' \) -print0 \
    | xargs -0 perl -pi -e 's/[ \t]+$//'

echo "==> Stamping MARMOT_VERSION"
MDK_SHA="$(git -C "$MDK_DIR" rev-parse --short HEAD)"
MDK_BRANCH="$(git -C "$MDK_DIR" rev-parse --abbrev-ref HEAD)"
MDK_TAG="$(git -C "$MDK_DIR" tag --points-at HEAD 2>/dev/null | head -1 || true)"
MDK_DIRTY=""
if ! git -C "$MDK_DIR" diff --quiet || ! git -C "$MDK_DIR" diff --cached --quiet; then
    MDK_DIRTY="-dirty"
fi
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
FEATURES="default"
if [[ "${OTLP_EXPORT:-0}" == "1" || "${OTLP_EXPORT:-}" == "true" ]]; then
    FEATURES="otlp-export"
fi

cat > "$VENDOR_DIR/MARMOT_VERSION" <<EOF
mdk-sha: ${MDK_SHA}${MDK_DIRTY}
mdk-branch: ${MDK_BRANCH}
mdk-tag: ${MDK_TAG:-}
built-at: ${BUILT_AT}
uniffi-version: 0.28.3
features: ${FEATURES}
ios-targets: aarch64-apple-ios, aarch64-apple-ios-sim
ios-deployment-target: 18.0

Notes:
- Regenerate with: whitenoise-ios/scripts/sync-bindings.sh
- A "-dirty" suffix means the MDK working tree had uncommitted
  changes when this bundle was built.
EOF

# Strip trailing whitespace (an empty `mdk-tag:` value would otherwise
# leave a trailing space that fails the repo's `git diff --check` gate).
sed -i '' -e 's/[[:space:]]*$//' "$VENDOR_DIR/MARMOT_VERSION"

# Compile-time version constant the app reads (Bundle.main can't see the
# MARMOT_VERSION text file, so we surface the SHA via Swift instead).
cat > "$VENDOR_DIR/Sources/MarmotKit/MarmotKitVersion.swift" <<EOF
import Foundation

/// Build-time provenance for this vendored MarmotKit bundle.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every rebuild.
public enum MarmotKitVersion {
    public static let mdkSHA = "${MDK_SHA}${MDK_DIRTY}"
    public static let mdkTag = "${MDK_TAG:-}"
    public static let builtAt = "${BUILT_AT}"
    public static let uniffiVersion = "0.28.3"
    public static let features = "${FEATURES}"
}
EOF

echo ""
echo "Done. Vendored MarmotKit @ ${MDK_SHA}${MDK_DIRTY} (${MDK_BRANCH}${MDK_TAG:+, tag: ${MDK_TAG}}, features: ${FEATURES})."
echo "Next: build & run the app in Xcode (Cmd+R)."
echo "If Xcode shows stale symbols, reset the package cache:"
echo "  File > Packages > Reset Package Caches, then clean build (Shift+Cmd+K)."
